package com.boding.mapper.authorityManagement;

import com.boding.pojo.authorityManagement.Right;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int deleteByPrimaryKey(Integer rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int insert(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int insertSelective(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    Right selectByPrimaryKey(Integer rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int updateByPrimaryKeySelective(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int updateByPrimaryKey(Right record);
}