package com.boding.mapper.authorityManagement;

import com.boding.pojo.authorityManagement.Rolerightrelation;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RolerightrelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int deleteByPrimaryKey(Integer rrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int insert(Rolerightrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int insertSelective(Rolerightrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    Rolerightrelation selectByPrimaryKey(Integer rrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int updateByPrimaryKeySelective(Rolerightrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int updateByPrimaryKey(Rolerightrelation record);

    //给角色授权
    void insertRoleRight(@Param("roleId")int roleId,@Param("rId")int rId,@Param("rType")int rType);
}