package com.boding.mapper.authorityManagement;

import com.boding.pojo.authorityManagement.Role;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    Role selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int updateByPrimaryKey(Role record);
    //添加角色
    void insertRole(@Param("roleName") String roleName, @Param("roleDate") Date roleDate, @Param("description") String description);

    //查询所有角色
    List<Role> selectAllRole();

    //通过ID查询角色
    Role selectRoleById(int id);

    //根据ID删除角色
    void deleteRoleById(int id);

    //根据ID修改角色属性
    void updateRoleById(@Param("id") int id,@Param("roleName")String roleName,@Param("description")String description);

    //根据角色名称查询记录数
    Long selectCountByName(String roleName);

    //根据角色名查询角色信息
    Role selectRoleByName(String roleName);
}