package com.boding.mapper.authorityManagement;

import com.boding.pojo.authorityManagement.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int updateByPrimaryKey(User record);

    //添加用户
    void insertUser(User user);

    //查询所有用户
    List<User> selectAllUser();

    //根据用户名查询用户
    User selectUserByName(String userName);

    //根据ID查询用户
    User selectUserById(int id);

    //修改密码
    void updateUserPsd(@Param("id")int id,@Param("oldUserPsd") String oldUserPsd, @Param("newUserPsd") String newUserPsd);

    //根据用户名查询count
    Long selectCountByName(String userName);

    //根据用户ID删除用户
    void deleteUserById(int userId);
}