package com.boding.mapper.authorityManagement;

import com.boding.pojo.authorityManagement.Userrolerelation;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserrolerelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int deleteByPrimaryKey(Integer urId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int insert(Userrolerelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int insertSelective(Userrolerelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    Userrolerelation selectByPrimaryKey(Integer urId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int updateByPrimaryKeySelective(Userrolerelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    int updateByPrimaryKey(Userrolerelation record);

    //授权用户角色
    void insertUserRole(Userrolerelation userrole);

    //取消授权
    void deleteUserRole(int userId);
}