package com.boding.pojo.authorityManagement;

public class Right {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.r_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.parent_r_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Integer parentRId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.right_name
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private String rightName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.description
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.r_id
     *
     * @return the value of right.r_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.r_id
     *
     * @param rId the value for right.r_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.parent_r_id
     *
     * @return the value of right.parent_r_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Integer getParentRId() {
        return parentRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.parent_r_id
     *
     * @param parentRId the value for right.parent_r_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setParentRId(Integer parentRId) {
        this.parentRId = parentRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.right_name
     *
     * @return the value of right.right_name
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.right_name
     *
     * @param rightName the value for right.right_name
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setRightName(String rightName) {
        this.rightName = rightName == null ? null : rightName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.description
     *
     * @return the value of right.description
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.description
     *
     * @param description the value for right.description
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}