package com.boding.pojo.authorityManagement;

public class Rolerightrelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.rr_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Integer rrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.role_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.r_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.r_type
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Integer rType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.rr_id
     *
     * @return the value of rolerightrelation.rr_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Integer getRrId() {
        return rrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.rr_id
     *
     * @param rrId the value for rolerightrelation.rr_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setRrId(Integer rrId) {
        this.rrId = rrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.role_id
     *
     * @return the value of rolerightrelation.role_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.role_id
     *
     * @param roleId the value for rolerightrelation.role_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.r_id
     *
     * @return the value of rolerightrelation.r_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.r_id
     *
     * @param rId the value for rolerightrelation.r_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.r_type
     *
     * @return the value of rolerightrelation.r_type
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Integer getrType() {
        return rType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.r_type
     *
     * @param rType the value for rolerightrelation.r_type
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setrType(Integer rType) {
        this.rType = rType;
    }
}