package com.boding.pojo.authorityManagement;

public class Userrolerelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrolerelation.ur_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Integer urId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrolerelation.user_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrolerelation.role_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrolerelation.ur_id
     *
     * @return the value of userrolerelation.ur_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Integer getUrId() {
        return urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrolerelation.ur_id
     *
     * @param urId the value for userrolerelation.ur_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setUrId(Integer urId) {
        this.urId = urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrolerelation.user_id
     *
     * @return the value of userrolerelation.user_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrolerelation.user_id
     *
     * @param userId the value for userrolerelation.user_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrolerelation.role_id
     *
     * @return the value of userrolerelation.role_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrolerelation.role_id
     *
     * @param roleId the value for userrolerelation.role_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}