package com.boding.pojo.authorityManagement;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_psd
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private String userPsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_date
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    private Date userDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_psd
     *
     * @return the value of user.user_psd
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public String getUserPsd() {
        return userPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_psd
     *
     * @param userPsd the value for user.user_psd
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setUserPsd(String userPsd) {
        this.userPsd = userPsd == null ? null : userPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_date
     *
     * @return the value of user.user_date
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public Date getUserDate() {
        return userDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_date
     *
     * @param userDate the value for user.user_date
     *
     * @mbggenerated Fri Sep 06 10:54:47 CST 2019
     */
    public void setUserDate(Date userDate) {
        this.userDate = userDate;
    }
}